Semana 8/Día 3/ProyectoPeliculas/Controllers/PeliculaController.cs
#pragma warning disable CS8618

using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using ProyectoPeliculas.Models;

namespace ProyectoPeliculas.Controllers;

public class PeliculaController : Controller{
    public static List<Director> ListaDirectores = new List<Director>();

    private readonly ILogger<PeliculaController> _logger;
    private MyContext _context;

    public PeliculaController(ILogger<PeliculaController> logger, MyContext context){
        _logger = logger;
        _context = context;
    }
    /* RUTAS GET */
    [HttpGet]
    [SessionCheck]
    [Route("peliculas")]
    public IActionResult Peliculas(){
        List<Pelicula> ListaPeliculas = _context.Peliculas.ToList();
        return View("Peliculas", ListaPeliculas);
    }

    [HttpGet]
    [SessionCheck]
    [Route("formulario/pelicula")]
    public IActionResult FormularioPelicula(){
        return View("FormularioPelicula");
    }

    [HttpGet]
    [SessionCheck]
    [Route("formulario/editar/pelicula/{id_pelicula}")]
    public IActionResult FormularioEditarPelicula(int id_pelicula){
        Pelicula? pelicula = _context.Peliculas.FirstOrDefault(peli => peli.Id == id_pelicula);
        return View("FormularioEditarPelicula", pelicula);
    }

    /* RUTAS POST */
    [HttpPost]
    [Route("nueva/pelicula")]
    public IActionResult AgregarPelicula(Pelicula pelicula){
        string? email = HttpContext.Session.GetString("Email");
        if(email == null){
            return View("Login");
        }
        if(ModelState.IsValid){
            /* INSERT INTO pelicula(titulo, genero, anio, descripcion, director_id)
               VALUES(titulo, genero, anio, descripcion, director_id); */
            _context.Peliculas.Add(pelicula);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View("FormularioPelicula");
    }

    [HttpPost]
    [Route("elimina/pelicula/{id_pelicula}")]
    public IActionResult EliminaPelicula(int id_pelicula){
        Pelicula? pelicula = _context.Peliculas.FirstOrDefault(peli => peli.Id == id_pelicula);
        _context.Peliculas.Remove(pelicula);
        _context.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpPost]
    [Route("actualiza/pelicula/{id_pelicula}")]
    public IActionResult ActualizaPelicula(Pelicula pelicula, int id_pelicula){
        Pelicula? peliculaPrevia = _context.Peliculas.FirstOrDefault(peli => peli.Id == id_pelicula);

        if(ModelState.IsValid){
            peliculaPrevia.Titulo = pelicula.Titulo;
            peliculaPrevia.Genero = pelicula.Genero;
            peliculaPrevia.Anio = pelicula.Anio;
            peliculaPrevia.Descripcion = pelicula.Descripcion;
            //peliculaPrevia.Fecha_Actualizacion = DateTime.Now;
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View("FormularioEditarPelicula", peliculaPrevia);

    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error(){
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Semana 8/Día 3/ProyectoPeliculas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoPeliculas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoPeliculas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Pelicula" asp-action="Peliculas">ProyectoPeliculas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(@Context.Session.GetString("Nombre") == null ){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Director" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Director" asp-action="Registro">Registro</a>
                            </li>
                        }
                        else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Pelicula" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Director" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Director" asp-action="Directores">Directores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Director" asp-action="ProcesaLogout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProyectoPeliculas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>